"use client";
import { useRouter } from "next/navigation"; import { useState } from "react";
import { ADMIN_OPTS, STATUSES, type AdminData } from "@/lib/form";
import type { Intake } from "@/lib/db";
export function Logout() { const r = useRouter(); return <button className="btn-o !py-2 text-sm" onClick={async () => { await fetch("/api/admin/login", { method: "DELETE" }); r.replace("/admin/login"); r.refresh(); }}>Sign out</button>; }
export function SettingsForm({ location, intake }: { location: string; intake: Intake }) {
  const [v, setV] = useState(location), [m, setM] = useState("");
  const [i, setI] = useState(intake);
  return <div className="space-y-6"><form className="flex flex-wrap items-end gap-2" onSubmit={async (e) => { e.preventDefault(); const r = await fetch("/api/admin/settings", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ location: v, intake: i }) }); setM(r.ok ? "Saved" : "Couldn't save"); }}>
    <div><label htmlFor="loc" className="mb-1 block text-sm text-white/60">Internship location (shown on the public site)</label><input id="loc" className="input !w-80 !py-2" value={v} onChange={(e) => setV(e.target.value)} /></div><label className="flex min-h-11 items-center gap-2"><input type="checkbox" checked={i.open} onChange={(e) => setI({ ...i, open: e.target.checked })} /> Intake open</label><div><label htmlFor="deadline" className="mb-1 block text-sm text-white/60">Deadline (optional)</label><input id="deadline" type="date" className="input !py-2" value={i.deadline} onChange={(e) => setI({ ...i, deadline: e.target.value })} /></div><div><label htmlFor="cap-video" className="mb-1 block text-sm text-white/60">Video cap (0 = none)</label><input id="cap-video" type="number" min="0" className="input !w-36 !py-2" value={i.capVideo} onChange={(e) => setI({ ...i, capVideo: Number(e.target.value) })} /></div><div><label htmlFor="cap-design" className="mb-1 block text-sm text-white/60">Design cap (0 = none)</label><input id="cap-design" type="number" min="0" className="input !w-36 !py-2" value={i.capDesign} onChange={(e) => setI({ ...i, capDesign: Number(e.target.value) })} /></div><button className="btn-o !py-2">Save settings</button><span role="status" className="text-sm text-y">{m}</span></form></div>;
}
export default function AdminControls({ id, admin }: { id: string; admin: AdminData }) {
  const [a, setA] = useState(admin), [note, setNote] = useState(""), [m, setM] = useState(""), [busy, setBusy] = useState(false);
  async function save(patch: object) { setBusy(true); setM(""); const r = await fetch(`/api/admin/applications/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(patch) }); setBusy(false);
    if (r.ok) { setA((await r.json()).admin); setM("Saved"); if ("note" in patch) setNote(""); } else setM("Couldn't save. Try again."); }
  const today = new Date().toISOString().slice(0, 10);
  const sel = (k: keyof typeof ADMIN_OPTS | "status", l: string, o: readonly string[]) => <div key={k}><label htmlFor={k} className="mb-1 block text-sm text-white/60">{l}</label><select id={k} className="input" value={(a as any)[k]} onChange={(e) => save({ [k]: e.target.value })}>{o.map((x) => <option key={x}>{x}</option>)}</select></div>;
  return (<div className="space-y-6"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{sel("status", "Application status", STATUSES)}{(Object.keys(ADMIN_OPTS) as (keyof typeof ADMIN_OPTS)[]).map((k) => sel(k, k.replace(/([A-Z])/g, " $1").replace(/^./, (c) => c.toUpperCase()), ADMIN_OPTS[k]))}</div>
    <div className="flex flex-wrap items-end gap-3">{(["internshipStart", "internshipEnd"] as const).map((k) => <div key={k}><label htmlFor={k} className="mb-1 block text-sm text-white/60">{k === "internshipStart" ? "Internship start" : "Internship end"}</label><input id={k} type="date" className="input !py-2" value={a[k]} onChange={(e) => save({ [k]: e.target.value })} /></div>)}
      <button className="btn-y !py-2" disabled={busy} onClick={() => save({ status: "INTERNSHIP STARTED", internshipStart: a.internshipStart || today })}>Mark internship started</button>
      <button className="btn-o !py-2" disabled={busy} onClick={() => save({ status: "COMPLETED", completionStatus: "Completed", internshipEnd: a.internshipEnd || today })}>Mark internship completed</button><span role="status" className="text-sm text-y">{m}</span></div>
    <div><h3 className="text-xl font-bold">Internal notes</h3><ul className="mt-3 space-y-2">{a.notes.map((n, i) => <li key={i} className="rounded-xl bg-white/5 p-3 text-sm"><span className="text-white/40">{n.at.slice(0, 16).replace("T", " ")} · </span>{n.text}</li>)}{!a.notes.length && <li className="text-sm text-white/40">No notes yet.</li>}</ul>
      <label htmlFor="note" className="sr-only">Internal note</label><textarea id="note" rows={3} className="input mt-3" placeholder="Visible to admins only" value={note} onChange={(e) => setNote(e.target.value)} /><button className="btn-y mt-2 !py-2" disabled={busy || !note.trim()} onClick={() => save({ note })}>Add Internal Note</button></div></div>);
}
