"use client";
import Link from "next/link"; import { useMemo, useState } from "react"; import { STATUSES } from "@/lib/form";
export type Row = { id: string; name: string; role: string; duration: string; college: string; exp: string; date: string; status: string };
export default function Applicants({ rows: init }: { rows: Row[] }) {
  const [rows, setRows] = useState(init), [q, setQ] = useState(""), [f, setF] = useState({ role: "", duration: "", status: "", college: "" }), [asc, setAsc] = useState(false), [err, setErr] = useState("");
  const colleges = useMemo(() => Array.from(new Set(rows.map((r) => r.college))).sort(), [rows]);
  const list = rows.filter((r) => (!q || `${r.name} ${r.id} ${r.college}`.toLowerCase().includes(q.toLowerCase())) && (!f.role || r.role === f.role) && (!f.duration || r.duration === f.duration) && (!f.status || r.status === f.status) && (!f.college || r.college === f.college)).sort((a, b) => (asc ? 1 : -1) * a.date.localeCompare(b.date));
  async function setStatus(id: string, status: string) { setErr(""); const res = await fetch(`/api/admin/applications/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status }) }); if (res.ok) setRows((p) => p.map((r) => (r.id === id ? { ...r, status } : r))); else setErr("Couldn't update status."); }
  const sel = (k: keyof typeof f, label: string, opts: string[]) => <select aria-label={label} className="input !w-auto !py-2" value={f[k]} onChange={(e) => setF({ ...f, [k]: e.target.value })}><option value="">{label}</option>{opts.map((o) => <option key={o}>{o}</option>)}</select>;
  return (<div><div className="mb-3 flex justify-end"><a href="/api/admin/export" className="btn-o min-h-11 !py-2 text-sm">Export CSV</a></div><details className="mb-4 rounded-2xl border border-white/10 p-3 md:hidden"><summary className="cursor-pointer list-none font-semibold text-y">Filters and search</summary><div className="mt-3 grid gap-2">{<input aria-label="Search applicants" placeholder="Search name, ID, college" className="input !py-2" value={q} onChange={(e) => setQ(e.target.value)} />}{sel("role", "All roles", ["Video Editing", "Graphic Designing"])}{sel("duration", "All durations", ["3 Months", "6 Months"])}{sel("status", "All statuses", STATUSES)}{sel("college", "All colleges", colleges)}</div></details><div className="mb-4 hidden flex-wrap gap-2 md:flex"><input aria-label="Search applicants" placeholder="Search name, ID, college" className="input !w-64 !py-2" value={q} onChange={(e) => setQ(e.target.value)} />
    {sel("role", "All roles", ["Video Editing", "Graphic Designing"])}{sel("duration", "All durations", ["3 Months", "6 Months"])}{sel("status", "All statuses", STATUSES)}{sel("college", "All colleges", colleges)}</div>
    {err && <p role="alert" className="mb-2 text-sm text-red-400">{err}</p>}
    <div className="space-y-3 md:hidden">{list.map((r) => <article key={r.id} className="rounded-2xl border border-white/10 p-4"><div className="flex items-start justify-between gap-3"><div><Link href={`/admin/${r.id}`} className="break-all text-lg font-semibold text-y">{r.name}</Link><p className="break-all text-sm text-white/55">{r.id}</p></div><Link href={`/admin/${r.id}`} className="grid min-h-11 min-w-11 place-items-center rounded-xl border border-white/20 text-sm text-y">View</Link></div><dl className="mt-4 grid grid-cols-2 gap-3 text-sm"><div><dt className="text-white/45">Role</dt><dd>{r.role}</dd></div><div><dt className="text-white/45">Applied</dt><dd>{r.date}</dd></div><div><dt className="text-white/45">Duration</dt><dd>{r.duration}</dd></div><div><dt className="text-white/45">College</dt><dd className="break-words">{r.college}</dd></div></dl><label className="mt-4 block text-sm text-white/55">Status{setStatus && <select aria-label={`Status for ${r.name}`} className="input mt-1" value={r.status} onChange={(e) => setStatus(r.id, e.target.value)}>{STATUSES.map((s) => <option key={s}>{s}</option>)}</select>}</label></article>)}{!list.length && <p className="rounded-2xl border border-white/10 p-8 text-center text-white/50">No applications match.</p>}</div><div className="hidden overflow-x-auto rounded-2xl border border-white/10 md:block"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-white/5 text-white/50"><tr>{["Application ID", "Applicant", "Role", "Duration", "College", "Experience"].map((h) => <th key={h} className="p-3 font-medium">{h}</th>)}<th className="p-3 font-medium"><button onClick={() => setAsc(!asc)} className="min-h-11 hover:text-y">Applied {asc ? "↑" : "↓"}</button></th><th className="p-3 font-medium">Status</th><th className="p-3" /></tr></thead>
      <tbody className="divide-y divide-white/10">{list.map((r) => <tr key={r.id} className="hover:bg-white/[.03]"><td className="p-3 tabular-nums">{r.id}</td><td className="p-3 font-semibold">{r.name}</td><td className="p-3">{r.role}</td><td className="p-3">{r.duration}</td><td className="p-3">{r.college}</td><td className="p-3">{r.exp}</td><td className="p-3">{r.date}</td>
        <td className="p-3"><select aria-label={`Status for ${r.name}`} className="input !w-auto !py-1.5 !text-xs" value={r.status} onChange={(e) => setStatus(r.id, e.target.value)}>{STATUSES.map((s) => <option key={s}>{s}</option>)}</select></td>
        <td className="p-3"><Link href={`/admin/${r.id}`} className="text-y hover:underline">View</Link></td></tr>)}
        {!list.length && <tr><td colSpan={9} className="p-8 text-center text-white/50">No applications match. Clear a filter to see more.</td></tr>}</tbody></table></div></div>);
}
