import Link from "next/link"; import { notFound, redirect } from "next/navigation";
import { isAdmin } from "@/lib/auth"; import { getApp } from "@/lib/db"; import { ROLES, ROLE_Q, type Role } from "@/lib/form"; import AdminControls from "@/components/AdminControls";
export const dynamic = "force-dynamic"; export const metadata = { robots: { index: false } };
const Sec = ({ t, children }: { t: string; children: React.ReactNode }) => <section className="glass p-6"><h2 className="display mb-4 text-2xl font-extrabold text-y">{t}</h2>{children}</section>;
const KV = ({ rows }: { rows: [string, string | number][] }) => <dl className="grid gap-x-8 gap-y-3 sm:grid-cols-2">{rows.filter((r) => r[1] !== "").map(([k, v]) => <div key={k}><dt className="text-xs text-white/45">{k}</dt><dd className="break-words">{v}</dd></div>)}</dl>;
const Btn = ({ href, children }: { href: string; children: React.ReactNode }) => <a href={href} target="_blank" rel="noopener noreferrer" className="btn-y !py-2 text-sm">{children}</a>;
export default async function Profile({ params }: { params: { id: string } }) {
  if (!(await isAdmin())) redirect("/admin/login");
  const a = await getApp(params.id); if (!a) notFound(); const d = a.data, Q = ROLE_Q[d.role as Role];
  return (<div className="mx-auto max-w-4xl space-y-5 px-5 py-8"><Link href="/admin" className="text-sm text-y hover:underline">← All applicants</Link>
    <h1 className="text-5xl font-extrabold">{d.fullName}</h1><p className="text-white/60">{a.id} · {ROLES[d.role as Role]} · {d.duration} · Excel: {a.excel}</p>
    <Sec t="Personal information"><KV rows={[["Email", d.email], ["Phone", d.phone], ["City", d.city], ["Current location", d.location], ["LinkedIn", d.linkedin], ["GitHub", d.github]]} /></Sec>
    <Sec t="Education"><KV rows={[["College", d.college], ["Degree/Course", d.degree], ["Year", d.year], ["Semester", d.semester], ["University/Board", d.university], ["College email", d.collegeEmail], ["College requires NOC letter", d.noc], ["NOC requirements", d.nocReq], ["Expected start", d.startDate], ["Expected end", d.endDate]]} /></Sec>
    <Sec t="Internship preference"><KV rows={[["Role", ROLES[d.role as Role]], ["Duration", d.duration], ["Comfortable with offline", d.offline]]} /></Sec>
    <Sec t="Role-specific skills"><KV rows={[[Q.toolsL, d.tools.join(", ")], [Q.expL, d.experience], [Q.skillL, `${d.rating} / 5`], [Q.typesL, d.types.join(", ")], ["Client projects", d.client + (d.clientDesc ? ` — ${d.clientDesc}` : "")]]} /></Sec>
    <Sec t="Portfolio / demo work"><div className="flex flex-wrap gap-2">{d.portfolio && <Btn href={d.portfolio}>Open demo work</Btn>}{d.portfolioSite && <Btn href={d.portfolioSite}>Portfolio website</Btn>}{d.linkedin && <Btn href={d.linkedin}>LinkedIn</Btn>}{d.github && <Btn href={d.github}>GitHub</Btn>}</div>{!d.portfolio && !d.portfolioSite && !d.linkedin && !d.github && !d.files.length && <p className="text-white/50">No portfolio or demo work provided.</p>}<p className="mt-3 break-all text-sm text-white/50">{d.portfolio}</p></Sec>
    <Sec t="Application answers"><div className="space-y-4">{[[Q.goodL, d.good], [Q.whyL, d.why]].map(([q, x]) => <div key={q}><p className="text-xs text-white/45">{q}</p><p className="whitespace-pre-wrap">{x}</p></div>)}</div></Sec>
    <Sec t="Documents">{d.files.length ? <ul className="space-y-4">{d.files.map((f, i) => { const ext = f.stored.split(".").pop(), url = `/api/admin/files/${a.id}/${i}`; return <li key={i}><div className="flex flex-wrap items-center gap-3"><span>{f.name} <span className="text-white/40">({(f.size / 1048576).toFixed(1)} MB)</span></span><a className="text-y hover:underline" href={url + "?dl=1"}>Download</a></div>
      {(ext === "png" || ext === "jpg" || ext === "jpeg") && /* eslint-disable-next-line @next/next/no-img-element */ <img src={url} alt={f.name} className="mt-2 max-h-72 rounded-xl" />}{(ext === "mp4" || ext === "mov") && <video src={url} controls preload="metadata" className="mt-2 max-h-72 rounded-xl" />}{ext === "pdf" && <a className="text-sm text-y hover:underline" href={url} target="_blank" rel="noopener noreferrer">Preview PDF</a>}</li>; })}</ul> : <p className="text-white/50">No files uploaded.</p>}</Sec>
    <Sec t="Status, notes & updates"><AdminControls id={a.id} admin={a.admin} /><form className="mt-5" action={`/api/admin/applications/${a.id}/retry-excel`} method="post"><button className="btn-o !py-2">Retry Excel sync</button></form></Sec></div>);
}
